const paintings = [{
        id: 1,
        author: 'Иван Крамской',
        title: 'Портрет Павла Михайловича Третьякова',
        material: 'холст',
        technique: 'масло',
        patron: true,
        style: 'портрет',
        src: 'https://www.tretyakovgallery.ru/upload/iblock/21b/21bb3ecf03fece65d97af0023c48713e.jpg',
    }, {
        id: 2,
        author: 'Василий Поленов',
        title: 'Московский дворик',
        material: 'холст',
        technique: 'масло',
        patron: false,
        style: '',
        src: 'https://www.tretyakovgallery.ru/upload/iblock/ef9/ef92a9ded7602c5c578bcbb82170f34d.jpg',
    }, {
        id: 3,
        author: 'Лидия Мастеркова',
        title: 'Композиция',
        material: 'холст',
        technique: 'масло',
        patron: true,
        style: '',
        src: 'https://www.tretyakovgallery.ru/upload/iblock/ec5/ec53d2689503be40f14e08d5eb84f2b1.jpg',
    },
    {
        id: 4,
        author: 'Илья Репин',
        title: 'Портрет Л.Н.Андреева',
        material: 'холст',
        technique: 'масло',
        patron: true,
        style: 'портрет',
        src: 'https://www.tretyakovgallery.ru/upload/iblock/53b/53b7e4bb409fdac44cbb3cabb0898a90.jpg',
    }, {
        id: 5,
        author: 'Зинаида Серебрякова',
        title: 'За туалетом. Автопортрет',
        material: 'Холст На Картоне',
        technique: 'масло',
        patron: false,
        style: 'портрет',
        src: 'https://www.tretyakovgallery.ru/upload/iblock/5f9/5f93171e021ff62ad408071188b6bf56.jpg',
    }, {
        id: 6,
        author: 'Станислав Жуковский',
        title: 'Терраса в поместье',
        material: 'холст',
        technique: 'масло',
        patron: true,
        style: '',
        src: 'https://www.tretyakovgallery.ru/upload/iblock/d32/d3242dee154471796bf59e830491a84d.jpg',
    }, {
        id: 7,
        author: 'Константин Коровин',
        title: 'На берегу моря в Крыму',
        material: 'холст',
        technique: 'масло',
        patron: true,
        style: '',
        src: 'https://www.tretyakovgallery.ru/upload/iblock/726/726ba638e38b6620a9f4b9b391b6d44c.jpg',
    }, {
        id: 8,
        author: 'Наталия Гончарова',
        title: 'Троица',
        material: 'холст',
        technique: 'масло',
        patron: true,
        style: '',
        src: 'https://www.tretyakovgallery.ru/upload/iblock/d6e/d6e977245e7b0c008d3548e0f4a5fd46.jpg',
    }, {
        id: 9,
        author: 'Константин Коровин',
        title: 'В саду. Гурзуф',
        material: 'холст',
        technique: 'масло',
        patron: false,
        style: '',
        src: 'https://www.tretyakovgallery.ru/upload/iblock/838/83841cb9172865e30a52a377ff99c63c.jpg',
    }, {
        id: 10,
        author: 'Осип Браз',
        title: 'Портрет писателя Антона Павловича Чехова',
        material: 'холст',
        technique: 'масло',
        patron: true,
        style: 'портрет',
        src: 'https://www.tretyakovgallery.ru/upload/iblock/cfe/cfe14caf21c6326777d0929aadbab7ef.jpg',
    }, {
        id: 11,
        author: 'Иван Крамской',
        title: 'Христос в пустыне',
        material: 'холст',
        technique: 'масло',
        patron: false,
        style: '',
        src: 'https://www.tretyakovgallery.ru/upload/iblock/eea/eea106f948fd691ce801a3bb4e4652e1.jpg',
    },
    {
        id: 12,
        author: 'Андрей Рублев',
        title: 'Троица',
        material: 'дерево',
        technique: 'темпера',
        patron: true,
        style: '',
        src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Andrey_Rublev_-_%D0%A1%D0%B2._%D0%A2%D1%80%D0%BE%D0%B8%D1%86%D0%B0_-_Google_Art_Project.jpg/800px-Andrey_Rublev_-_%D0%A1%D0%B2._%D0%A2%D1%80%D0%BE%D0%B8%D1%86%D0%B0_-_Google_Art_Project.jpg',
    },
]